org: yvlfltyyuoliiuziesev
app: projeto-tarefas
service: projeto-tarefas

provider:
  name: aws
  runtime: nodejs20.x

functions:
  api:
    handler: src/handler.main
    events:
      - httpApi: "*"

plugins:
  - serverless-offline
